// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/cometbft/cometbft/abci/types"
)

// AppConnPrefetch is an autogenerated mock type for the AppConnPrefetch type
type AppConnPrefetch struct {
	mock.Mock
}

// PreBeginBlockSync provides a mock function with given fields: _a0
func (_m *AppConnPrefetch) PreBeginBlockSync(_a0 types.RequestPreBeginBlock) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.RequestPreBeginBlock) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PreCommitSync provides a mock function with given fields: _a0
func (_m *AppConnPrefetch) PreCommitSync(_a0 types.RequestPreCommit) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(types.RequestPreCommit) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PreDeliverTxAsync provides a mock function with given fields: _a0
func (_m *AppConnPrefetch) PreDeliverTxAsync(_a0 types.RequestPreDeliverTx) {
	_m.Called(_a0)
}

type mockConstructorTestingTNewAppConnPrefetch interface {
	mock.TestingT
	Cleanup(func())
}

// NewAppConnPrefetch creates a new instance of AppConnPrefetch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAppConnPrefetch(t mockConstructorTestingTNewAppConnPrefetch) *AppConnPrefetch {
	mock := &AppConnPrefetch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
