// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	types "github.com/cometbft/cometbft/abci/types"
)

// AppConnPrefetch is an autogenerated mock type for the AppConnPrefetch type
type AppConnPrefetch struct {
	mock.Mock
}

type AppConnPrefetch_Expecter struct {
	mock *mock.Mock
}

func (_m *AppConnPrefetch) EXPECT() *AppConnPrefetch_Expecter {
	return &AppConnPrefetch_Expecter{mock: &_m.Mock}
}

// PreBeginBlockSync provides a mock function with given fields: _a0
func (_m *AppConnPrefetch) PreBeginBlockSync(_a0 types.RequestPreBeginBlock) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for PreBeginBlockSync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.RequestPreBeginBlock) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AppConnPrefetch_PreBeginBlockSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreBeginBlockSync'
type AppConnPrefetch_PreBeginBlockSync_Call struct {
	*mock.Call
}

// PreBeginBlockSync is a helper method to define mock.On call
//   - _a0 types.RequestPreBeginBlock
func (_e *AppConnPrefetch_Expecter) PreBeginBlockSync(_a0 interface{}) *AppConnPrefetch_PreBeginBlockSync_Call {
	return &AppConnPrefetch_PreBeginBlockSync_Call{Call: _e.mock.On("PreBeginBlockSync", _a0)}
}

func (_c *AppConnPrefetch_PreBeginBlockSync_Call) Run(run func(_a0 types.RequestPreBeginBlock)) *AppConnPrefetch_PreBeginBlockSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.RequestPreBeginBlock))
	})
	return _c
}

func (_c *AppConnPrefetch_PreBeginBlockSync_Call) Return(_a0 error) *AppConnPrefetch_PreBeginBlockSync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppConnPrefetch_PreBeginBlockSync_Call) RunAndReturn(run func(types.RequestPreBeginBlock) error) *AppConnPrefetch_PreBeginBlockSync_Call {
	_c.Call.Return(run)
	return _c
}

// PreCommitSync provides a mock function with given fields: _a0
func (_m *AppConnPrefetch) PreCommitSync(_a0 types.RequestPreCommit) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for PreCommitSync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.RequestPreCommit) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AppConnPrefetch_PreCommitSync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreCommitSync'
type AppConnPrefetch_PreCommitSync_Call struct {
	*mock.Call
}

// PreCommitSync is a helper method to define mock.On call
//   - _a0 types.RequestPreCommit
func (_e *AppConnPrefetch_Expecter) PreCommitSync(_a0 interface{}) *AppConnPrefetch_PreCommitSync_Call {
	return &AppConnPrefetch_PreCommitSync_Call{Call: _e.mock.On("PreCommitSync", _a0)}
}

func (_c *AppConnPrefetch_PreCommitSync_Call) Run(run func(_a0 types.RequestPreCommit)) *AppConnPrefetch_PreCommitSync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.RequestPreCommit))
	})
	return _c
}

func (_c *AppConnPrefetch_PreCommitSync_Call) Return(_a0 error) *AppConnPrefetch_PreCommitSync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AppConnPrefetch_PreCommitSync_Call) RunAndReturn(run func(types.RequestPreCommit) error) *AppConnPrefetch_PreCommitSync_Call {
	_c.Call.Return(run)
	return _c
}

// PreDeliverTxAsync provides a mock function with given fields: _a0
func (_m *AppConnPrefetch) PreDeliverTxAsync(_a0 types.RequestPreDeliverTx) {
	_m.Called(_a0)
}

// AppConnPrefetch_PreDeliverTxAsync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreDeliverTxAsync'
type AppConnPrefetch_PreDeliverTxAsync_Call struct {
	*mock.Call
}

// PreDeliverTxAsync is a helper method to define mock.On call
//   - _a0 types.RequestPreDeliverTx
func (_e *AppConnPrefetch_Expecter) PreDeliverTxAsync(_a0 interface{}) *AppConnPrefetch_PreDeliverTxAsync_Call {
	return &AppConnPrefetch_PreDeliverTxAsync_Call{Call: _e.mock.On("PreDeliverTxAsync", _a0)}
}

func (_c *AppConnPrefetch_PreDeliverTxAsync_Call) Run(run func(_a0 types.RequestPreDeliverTx)) *AppConnPrefetch_PreDeliverTxAsync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.RequestPreDeliverTx))
	})
	return _c
}

func (_c *AppConnPrefetch_PreDeliverTxAsync_Call) Return() *AppConnPrefetch_PreDeliverTxAsync_Call {
	_c.Call.Return()
	return _c
}

func (_c *AppConnPrefetch_PreDeliverTxAsync_Call) RunAndReturn(run func(types.RequestPreDeliverTx)) *AppConnPrefetch_PreDeliverTxAsync_Call {
	_c.Run(run)
	return _c
}

// NewAppConnPrefetch creates a new instance of AppConnPrefetch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAppConnPrefetch(t interface {
	mock.TestingT
	Cleanup(func())
}) *AppConnPrefetch {
	mock := &AppConnPrefetch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
