// Code generated by mockery. DO NOT EDIT.

package state

import (
	types "github.com/cometbft/cometbft/types"
	mock "github.com/stretchr/testify/mock"
)

// MockBlockStore is an autogenerated mock type for the BlockStore type
type MockBlockStore struct {
	mock.Mock
}

type MockBlockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockStore) EXPECT() *MockBlockStore_Expecter {
	return &MockBlockStore_Expecter{mock: &_m.Mock}
}

// Base provides a mock function with no fields
func (_m *MockBlockStore) Base() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Base")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockBlockStore_Base_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Base'
type MockBlockStore_Base_Call struct {
	*mock.Call
}

// Base is a helper method to define mock.On call
func (_e *MockBlockStore_Expecter) Base() *MockBlockStore_Base_Call {
	return &MockBlockStore_Base_Call{Call: _e.mock.On("Base")}
}

func (_c *MockBlockStore_Base_Call) Run(run func()) *MockBlockStore_Base_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockStore_Base_Call) Return(_a0 int64) *MockBlockStore_Base_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockStore_Base_Call) RunAndReturn(run func() int64) *MockBlockStore_Base_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLatestBlock provides a mock function with no fields
func (_m *MockBlockStore) DeleteLatestBlock() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DeleteLatestBlock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBlockStore_DeleteLatestBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLatestBlock'
type MockBlockStore_DeleteLatestBlock_Call struct {
	*mock.Call
}

// DeleteLatestBlock is a helper method to define mock.On call
func (_e *MockBlockStore_Expecter) DeleteLatestBlock() *MockBlockStore_DeleteLatestBlock_Call {
	return &MockBlockStore_DeleteLatestBlock_Call{Call: _e.mock.On("DeleteLatestBlock")}
}

func (_c *MockBlockStore_DeleteLatestBlock_Call) Run(run func()) *MockBlockStore_DeleteLatestBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockStore_DeleteLatestBlock_Call) Return(_a0 error) *MockBlockStore_DeleteLatestBlock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockStore_DeleteLatestBlock_Call) RunAndReturn(run func() error) *MockBlockStore_DeleteLatestBlock_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteLatestBlocks provides a mock function with given fields: n
func (_m *MockBlockStore) DeleteLatestBlocks(n uint64) error {
	ret := _m.Called(n)

	if len(ret) == 0 {
		panic("no return value specified for DeleteLatestBlocks")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(uint64) error); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBlockStore_DeleteLatestBlocks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteLatestBlocks'
type MockBlockStore_DeleteLatestBlocks_Call struct {
	*mock.Call
}

// DeleteLatestBlocks is a helper method to define mock.On call
//   - n uint64
func (_e *MockBlockStore_Expecter) DeleteLatestBlocks(n interface{}) *MockBlockStore_DeleteLatestBlocks_Call {
	return &MockBlockStore_DeleteLatestBlocks_Call{Call: _e.mock.On("DeleteLatestBlocks", n)}
}

func (_c *MockBlockStore_DeleteLatestBlocks_Call) Run(run func(n uint64)) *MockBlockStore_DeleteLatestBlocks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint64))
	})
	return _c
}

func (_c *MockBlockStore_DeleteLatestBlocks_Call) Return(_a0 error) *MockBlockStore_DeleteLatestBlocks_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockStore_DeleteLatestBlocks_Call) RunAndReturn(run func(uint64) error) *MockBlockStore_DeleteLatestBlocks_Call {
	_c.Call.Return(run)
	return _c
}

// Height provides a mock function with no fields
func (_m *MockBlockStore) Height() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Height")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockBlockStore_Height_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Height'
type MockBlockStore_Height_Call struct {
	*mock.Call
}

// Height is a helper method to define mock.On call
func (_e *MockBlockStore_Expecter) Height() *MockBlockStore_Height_Call {
	return &MockBlockStore_Height_Call{Call: _e.mock.On("Height")}
}

func (_c *MockBlockStore_Height_Call) Run(run func()) *MockBlockStore_Height_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockStore_Height_Call) Return(_a0 int64) *MockBlockStore_Height_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockStore_Height_Call) RunAndReturn(run func() int64) *MockBlockStore_Height_Call {
	_c.Call.Return(run)
	return _c
}

// LoadBaseMeta provides a mock function with no fields
func (_m *MockBlockStore) LoadBaseMeta() *types.BlockMeta {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadBaseMeta")
	}

	var r0 *types.BlockMeta
	if rf, ok := ret.Get(0).(func() *types.BlockMeta); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.BlockMeta)
		}
	}

	return r0
}

// MockBlockStore_LoadBaseMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadBaseMeta'
type MockBlockStore_LoadBaseMeta_Call struct {
	*mock.Call
}

// LoadBaseMeta is a helper method to define mock.On call
func (_e *MockBlockStore_Expecter) LoadBaseMeta() *MockBlockStore_LoadBaseMeta_Call {
	return &MockBlockStore_LoadBaseMeta_Call{Call: _e.mock.On("LoadBaseMeta")}
}

func (_c *MockBlockStore_LoadBaseMeta_Call) Run(run func()) *MockBlockStore_LoadBaseMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockStore_LoadBaseMeta_Call) Return(_a0 *types.BlockMeta) *MockBlockStore_LoadBaseMeta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockStore_LoadBaseMeta_Call) RunAndReturn(run func() *types.BlockMeta) *MockBlockStore_LoadBaseMeta_Call {
	_c.Call.Return(run)
	return _c
}

// LoadBlock provides a mock function with given fields: height
func (_m *MockBlockStore) LoadBlock(height int64) *types.Block {
	ret := _m.Called(height)

	if len(ret) == 0 {
		panic("no return value specified for LoadBlock")
	}

	var r0 *types.Block
	if rf, ok := ret.Get(0).(func(int64) *types.Block); ok {
		r0 = rf(height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Block)
		}
	}

	return r0
}

// MockBlockStore_LoadBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadBlock'
type MockBlockStore_LoadBlock_Call struct {
	*mock.Call
}

// LoadBlock is a helper method to define mock.On call
//   - height int64
func (_e *MockBlockStore_Expecter) LoadBlock(height interface{}) *MockBlockStore_LoadBlock_Call {
	return &MockBlockStore_LoadBlock_Call{Call: _e.mock.On("LoadBlock", height)}
}

func (_c *MockBlockStore_LoadBlock_Call) Run(run func(height int64)) *MockBlockStore_LoadBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockBlockStore_LoadBlock_Call) Return(_a0 *types.Block) *MockBlockStore_LoadBlock_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockStore_LoadBlock_Call) RunAndReturn(run func(int64) *types.Block) *MockBlockStore_LoadBlock_Call {
	_c.Call.Return(run)
	return _c
}

// LoadBlockByHash provides a mock function with given fields: hash
func (_m *MockBlockStore) LoadBlockByHash(hash []byte) *types.Block {
	ret := _m.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for LoadBlockByHash")
	}

	var r0 *types.Block
	if rf, ok := ret.Get(0).(func([]byte) *types.Block); ok {
		r0 = rf(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Block)
		}
	}

	return r0
}

// MockBlockStore_LoadBlockByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadBlockByHash'
type MockBlockStore_LoadBlockByHash_Call struct {
	*mock.Call
}

// LoadBlockByHash is a helper method to define mock.On call
//   - hash []byte
func (_e *MockBlockStore_Expecter) LoadBlockByHash(hash interface{}) *MockBlockStore_LoadBlockByHash_Call {
	return &MockBlockStore_LoadBlockByHash_Call{Call: _e.mock.On("LoadBlockByHash", hash)}
}

func (_c *MockBlockStore_LoadBlockByHash_Call) Run(run func(hash []byte)) *MockBlockStore_LoadBlockByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockBlockStore_LoadBlockByHash_Call) Return(_a0 *types.Block) *MockBlockStore_LoadBlockByHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockStore_LoadBlockByHash_Call) RunAndReturn(run func([]byte) *types.Block) *MockBlockStore_LoadBlockByHash_Call {
	_c.Call.Return(run)
	return _c
}

// LoadBlockCommit provides a mock function with given fields: height
func (_m *MockBlockStore) LoadBlockCommit(height int64) *types.Commit {
	ret := _m.Called(height)

	if len(ret) == 0 {
		panic("no return value specified for LoadBlockCommit")
	}

	var r0 *types.Commit
	if rf, ok := ret.Get(0).(func(int64) *types.Commit); ok {
		r0 = rf(height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Commit)
		}
	}

	return r0
}

// MockBlockStore_LoadBlockCommit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadBlockCommit'
type MockBlockStore_LoadBlockCommit_Call struct {
	*mock.Call
}

// LoadBlockCommit is a helper method to define mock.On call
//   - height int64
func (_e *MockBlockStore_Expecter) LoadBlockCommit(height interface{}) *MockBlockStore_LoadBlockCommit_Call {
	return &MockBlockStore_LoadBlockCommit_Call{Call: _e.mock.On("LoadBlockCommit", height)}
}

func (_c *MockBlockStore_LoadBlockCommit_Call) Run(run func(height int64)) *MockBlockStore_LoadBlockCommit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockBlockStore_LoadBlockCommit_Call) Return(_a0 *types.Commit) *MockBlockStore_LoadBlockCommit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockStore_LoadBlockCommit_Call) RunAndReturn(run func(int64) *types.Commit) *MockBlockStore_LoadBlockCommit_Call {
	_c.Call.Return(run)
	return _c
}

// LoadBlockMeta provides a mock function with given fields: height
func (_m *MockBlockStore) LoadBlockMeta(height int64) *types.BlockMeta {
	ret := _m.Called(height)

	if len(ret) == 0 {
		panic("no return value specified for LoadBlockMeta")
	}

	var r0 *types.BlockMeta
	if rf, ok := ret.Get(0).(func(int64) *types.BlockMeta); ok {
		r0 = rf(height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.BlockMeta)
		}
	}

	return r0
}

// MockBlockStore_LoadBlockMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadBlockMeta'
type MockBlockStore_LoadBlockMeta_Call struct {
	*mock.Call
}

// LoadBlockMeta is a helper method to define mock.On call
//   - height int64
func (_e *MockBlockStore_Expecter) LoadBlockMeta(height interface{}) *MockBlockStore_LoadBlockMeta_Call {
	return &MockBlockStore_LoadBlockMeta_Call{Call: _e.mock.On("LoadBlockMeta", height)}
}

func (_c *MockBlockStore_LoadBlockMeta_Call) Run(run func(height int64)) *MockBlockStore_LoadBlockMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockBlockStore_LoadBlockMeta_Call) Return(_a0 *types.BlockMeta) *MockBlockStore_LoadBlockMeta_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockStore_LoadBlockMeta_Call) RunAndReturn(run func(int64) *types.BlockMeta) *MockBlockStore_LoadBlockMeta_Call {
	_c.Call.Return(run)
	return _c
}

// LoadBlockMetaByHash provides a mock function with given fields: hash
func (_m *MockBlockStore) LoadBlockMetaByHash(hash []byte) *types.BlockMeta {
	ret := _m.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for LoadBlockMetaByHash")
	}

	var r0 *types.BlockMeta
	if rf, ok := ret.Get(0).(func([]byte) *types.BlockMeta); ok {
		r0 = rf(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.BlockMeta)
		}
	}

	return r0
}

// MockBlockStore_LoadBlockMetaByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadBlockMetaByHash'
type MockBlockStore_LoadBlockMetaByHash_Call struct {
	*mock.Call
}

// LoadBlockMetaByHash is a helper method to define mock.On call
//   - hash []byte
func (_e *MockBlockStore_Expecter) LoadBlockMetaByHash(hash interface{}) *MockBlockStore_LoadBlockMetaByHash_Call {
	return &MockBlockStore_LoadBlockMetaByHash_Call{Call: _e.mock.On("LoadBlockMetaByHash", hash)}
}

func (_c *MockBlockStore_LoadBlockMetaByHash_Call) Run(run func(hash []byte)) *MockBlockStore_LoadBlockMetaByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockBlockStore_LoadBlockMetaByHash_Call) Return(_a0 *types.BlockMeta) *MockBlockStore_LoadBlockMetaByHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockStore_LoadBlockMetaByHash_Call) RunAndReturn(run func([]byte) *types.BlockMeta) *MockBlockStore_LoadBlockMetaByHash_Call {
	_c.Call.Return(run)
	return _c
}

// LoadBlockPart provides a mock function with given fields: height, index
func (_m *MockBlockStore) LoadBlockPart(height int64, index int) *types.Part {
	ret := _m.Called(height, index)

	if len(ret) == 0 {
		panic("no return value specified for LoadBlockPart")
	}

	var r0 *types.Part
	if rf, ok := ret.Get(0).(func(int64, int) *types.Part); ok {
		r0 = rf(height, index)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Part)
		}
	}

	return r0
}

// MockBlockStore_LoadBlockPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadBlockPart'
type MockBlockStore_LoadBlockPart_Call struct {
	*mock.Call
}

// LoadBlockPart is a helper method to define mock.On call
//   - height int64
//   - index int
func (_e *MockBlockStore_Expecter) LoadBlockPart(height interface{}, index interface{}) *MockBlockStore_LoadBlockPart_Call {
	return &MockBlockStore_LoadBlockPart_Call{Call: _e.mock.On("LoadBlockPart", height, index)}
}

func (_c *MockBlockStore_LoadBlockPart_Call) Run(run func(height int64, index int)) *MockBlockStore_LoadBlockPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int))
	})
	return _c
}

func (_c *MockBlockStore_LoadBlockPart_Call) Return(_a0 *types.Part) *MockBlockStore_LoadBlockPart_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockStore_LoadBlockPart_Call) RunAndReturn(run func(int64, int) *types.Part) *MockBlockStore_LoadBlockPart_Call {
	_c.Call.Return(run)
	return _c
}

// LoadSeenCommit provides a mock function with given fields: height
func (_m *MockBlockStore) LoadSeenCommit(height int64) *types.Commit {
	ret := _m.Called(height)

	if len(ret) == 0 {
		panic("no return value specified for LoadSeenCommit")
	}

	var r0 *types.Commit
	if rf, ok := ret.Get(0).(func(int64) *types.Commit); ok {
		r0 = rf(height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.Commit)
		}
	}

	return r0
}

// MockBlockStore_LoadSeenCommit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadSeenCommit'
type MockBlockStore_LoadSeenCommit_Call struct {
	*mock.Call
}

// LoadSeenCommit is a helper method to define mock.On call
//   - height int64
func (_e *MockBlockStore_Expecter) LoadSeenCommit(height interface{}) *MockBlockStore_LoadSeenCommit_Call {
	return &MockBlockStore_LoadSeenCommit_Call{Call: _e.mock.On("LoadSeenCommit", height)}
}

func (_c *MockBlockStore_LoadSeenCommit_Call) Run(run func(height int64)) *MockBlockStore_LoadSeenCommit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockBlockStore_LoadSeenCommit_Call) Return(_a0 *types.Commit) *MockBlockStore_LoadSeenCommit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockStore_LoadSeenCommit_Call) RunAndReturn(run func(int64) *types.Commit) *MockBlockStore_LoadSeenCommit_Call {
	_c.Call.Return(run)
	return _c
}

// PruneBlocks provides a mock function with given fields: height
func (_m *MockBlockStore) PruneBlocks(height int64) (uint64, error) {
	ret := _m.Called(height)

	if len(ret) == 0 {
		panic("no return value specified for PruneBlocks")
	}

	var r0 uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (uint64, error)); ok {
		return rf(height)
	}
	if rf, ok := ret.Get(0).(func(int64) uint64); ok {
		r0 = rf(height)
	} else {
		r0 = ret.Get(0).(uint64)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(height)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBlockStore_PruneBlocks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneBlocks'
type MockBlockStore_PruneBlocks_Call struct {
	*mock.Call
}

// PruneBlocks is a helper method to define mock.On call
//   - height int64
func (_e *MockBlockStore_Expecter) PruneBlocks(height interface{}) *MockBlockStore_PruneBlocks_Call {
	return &MockBlockStore_PruneBlocks_Call{Call: _e.mock.On("PruneBlocks", height)}
}

func (_c *MockBlockStore_PruneBlocks_Call) Run(run func(height int64)) *MockBlockStore_PruneBlocks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockBlockStore_PruneBlocks_Call) Return(_a0 uint64, _a1 error) *MockBlockStore_PruneBlocks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBlockStore_PruneBlocks_Call) RunAndReturn(run func(int64) (uint64, error)) *MockBlockStore_PruneBlocks_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBlock provides a mock function with given fields: block, blockParts, seenCommit
func (_m *MockBlockStore) SaveBlock(block *types.Block, blockParts *types.PartSet, seenCommit *types.Commit) {
	_m.Called(block, blockParts, seenCommit)
}

// MockBlockStore_SaveBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBlock'
type MockBlockStore_SaveBlock_Call struct {
	*mock.Call
}

// SaveBlock is a helper method to define mock.On call
//   - block *types.Block
//   - blockParts *types.PartSet
//   - seenCommit *types.Commit
func (_e *MockBlockStore_Expecter) SaveBlock(block interface{}, blockParts interface{}, seenCommit interface{}) *MockBlockStore_SaveBlock_Call {
	return &MockBlockStore_SaveBlock_Call{Call: _e.mock.On("SaveBlock", block, blockParts, seenCommit)}
}

func (_c *MockBlockStore_SaveBlock_Call) Run(run func(block *types.Block, blockParts *types.PartSet, seenCommit *types.Commit)) *MockBlockStore_SaveBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*types.Block), args[1].(*types.PartSet), args[2].(*types.Commit))
	})
	return _c
}

func (_c *MockBlockStore_SaveBlock_Call) Return() *MockBlockStore_SaveBlock_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBlockStore_SaveBlock_Call) RunAndReturn(run func(*types.Block, *types.PartSet, *types.Commit)) *MockBlockStore_SaveBlock_Call {
	_c.Run(run)
	return _c
}

// Size provides a mock function with no fields
func (_m *MockBlockStore) Size() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockBlockStore_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockBlockStore_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockBlockStore_Expecter) Size() *MockBlockStore_Size_Call {
	return &MockBlockStore_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockBlockStore_Size_Call) Run(run func()) *MockBlockStore_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockStore_Size_Call) Return(_a0 int64) *MockBlockStore_Size_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBlockStore_Size_Call) RunAndReturn(run func() int64) *MockBlockStore_Size_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBlockStore creates a new instance of MockBlockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockStore {
	mock := &MockBlockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
