// Code generated by mockery. DO NOT EDIT.

package state

import (
	tendermintstate "github.com/cometbft/cometbft/proto/tendermint/state"
	types "github.com/cometbft/cometbft/types"
	mock "github.com/stretchr/testify/mock"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// Bootstrap provides a mock function with given fields: _a0
func (_m *MockStore) Bootstrap(_a0 State) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Bootstrap")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(State) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Bootstrap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Bootstrap'
type MockStore_Bootstrap_Call struct {
	*mock.Call
}

// Bootstrap is a helper method to define mock.On call
//   - _a0 State
func (_e *MockStore_Expecter) Bootstrap(_a0 interface{}) *MockStore_Bootstrap_Call {
	return &MockStore_Bootstrap_Call{Call: _e.mock.On("Bootstrap", _a0)}
}

func (_c *MockStore_Bootstrap_Call) Run(run func(_a0 State)) *MockStore_Bootstrap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(State))
	})
	return _c
}

func (_c *MockStore_Bootstrap_Call) Return(_a0 error) *MockStore_Bootstrap_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Bootstrap_Call) RunAndReturn(run func(State) error) *MockStore_Bootstrap_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function with no fields
func (_m *MockStore) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStore_Expecter) Close() *MockStore_Close_Call {
	return &MockStore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStore_Close_Call) Run(run func()) *MockStore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Close_Call) Return(_a0 error) *MockStore_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Close_Call) RunAndReturn(run func() error) *MockStore_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function with no fields
func (_m *MockStore) Load() (State, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 State
	var r1 error
	if rf, ok := ret.Get(0).(func() (State, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() State); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(State)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
func (_e *MockStore_Expecter) Load() *MockStore_Load_Call {
	return &MockStore_Load_Call{Call: _e.mock.On("Load")}
}

func (_c *MockStore_Load_Call) Run(run func()) *MockStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStore_Load_Call) Return(_a0 State, _a1 error) *MockStore_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_Load_Call) RunAndReturn(run func() (State, error)) *MockStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// LoadABCIResponses provides a mock function with given fields: _a0
func (_m *MockStore) LoadABCIResponses(_a0 int64) (*tendermintstate.ABCIResponses, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for LoadABCIResponses")
	}

	var r0 *tendermintstate.ABCIResponses
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*tendermintstate.ABCIResponses, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(int64) *tendermintstate.ABCIResponses); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tendermintstate.ABCIResponses)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_LoadABCIResponses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadABCIResponses'
type MockStore_LoadABCIResponses_Call struct {
	*mock.Call
}

// LoadABCIResponses is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockStore_Expecter) LoadABCIResponses(_a0 interface{}) *MockStore_LoadABCIResponses_Call {
	return &MockStore_LoadABCIResponses_Call{Call: _e.mock.On("LoadABCIResponses", _a0)}
}

func (_c *MockStore_LoadABCIResponses_Call) Run(run func(_a0 int64)) *MockStore_LoadABCIResponses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockStore_LoadABCIResponses_Call) Return(_a0 *tendermintstate.ABCIResponses, _a1 error) *MockStore_LoadABCIResponses_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_LoadABCIResponses_Call) RunAndReturn(run func(int64) (*tendermintstate.ABCIResponses, error)) *MockStore_LoadABCIResponses_Call {
	_c.Call.Return(run)
	return _c
}

// LoadConsensusParams provides a mock function with given fields: _a0
func (_m *MockStore) LoadConsensusParams(_a0 int64) (types.ConsensusParams, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for LoadConsensusParams")
	}

	var r0 types.ConsensusParams
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (types.ConsensusParams, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(int64) types.ConsensusParams); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(types.ConsensusParams)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_LoadConsensusParams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadConsensusParams'
type MockStore_LoadConsensusParams_Call struct {
	*mock.Call
}

// LoadConsensusParams is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockStore_Expecter) LoadConsensusParams(_a0 interface{}) *MockStore_LoadConsensusParams_Call {
	return &MockStore_LoadConsensusParams_Call{Call: _e.mock.On("LoadConsensusParams", _a0)}
}

func (_c *MockStore_LoadConsensusParams_Call) Run(run func(_a0 int64)) *MockStore_LoadConsensusParams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockStore_LoadConsensusParams_Call) Return(_a0 types.ConsensusParams, _a1 error) *MockStore_LoadConsensusParams_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_LoadConsensusParams_Call) RunAndReturn(run func(int64) (types.ConsensusParams, error)) *MockStore_LoadConsensusParams_Call {
	_c.Call.Return(run)
	return _c
}

// LoadFromDBOrGenesisDoc provides a mock function with given fields: _a0
func (_m *MockStore) LoadFromDBOrGenesisDoc(_a0 *types.GenesisDoc) (State, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for LoadFromDBOrGenesisDoc")
	}

	var r0 State
	var r1 error
	if rf, ok := ret.Get(0).(func(*types.GenesisDoc) (State, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(*types.GenesisDoc) State); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(State)
	}

	if rf, ok := ret.Get(1).(func(*types.GenesisDoc) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_LoadFromDBOrGenesisDoc_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadFromDBOrGenesisDoc'
type MockStore_LoadFromDBOrGenesisDoc_Call struct {
	*mock.Call
}

// LoadFromDBOrGenesisDoc is a helper method to define mock.On call
//   - _a0 *types.GenesisDoc
func (_e *MockStore_Expecter) LoadFromDBOrGenesisDoc(_a0 interface{}) *MockStore_LoadFromDBOrGenesisDoc_Call {
	return &MockStore_LoadFromDBOrGenesisDoc_Call{Call: _e.mock.On("LoadFromDBOrGenesisDoc", _a0)}
}

func (_c *MockStore_LoadFromDBOrGenesisDoc_Call) Run(run func(_a0 *types.GenesisDoc)) *MockStore_LoadFromDBOrGenesisDoc_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*types.GenesisDoc))
	})
	return _c
}

func (_c *MockStore_LoadFromDBOrGenesisDoc_Call) Return(_a0 State, _a1 error) *MockStore_LoadFromDBOrGenesisDoc_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_LoadFromDBOrGenesisDoc_Call) RunAndReturn(run func(*types.GenesisDoc) (State, error)) *MockStore_LoadFromDBOrGenesisDoc_Call {
	_c.Call.Return(run)
	return _c
}

// LoadFromDBOrGenesisFile provides a mock function with given fields: _a0
func (_m *MockStore) LoadFromDBOrGenesisFile(_a0 string) (State, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for LoadFromDBOrGenesisFile")
	}

	var r0 State
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (State, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) State); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(State)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_LoadFromDBOrGenesisFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadFromDBOrGenesisFile'
type MockStore_LoadFromDBOrGenesisFile_Call struct {
	*mock.Call
}

// LoadFromDBOrGenesisFile is a helper method to define mock.On call
//   - _a0 string
func (_e *MockStore_Expecter) LoadFromDBOrGenesisFile(_a0 interface{}) *MockStore_LoadFromDBOrGenesisFile_Call {
	return &MockStore_LoadFromDBOrGenesisFile_Call{Call: _e.mock.On("LoadFromDBOrGenesisFile", _a0)}
}

func (_c *MockStore_LoadFromDBOrGenesisFile_Call) Run(run func(_a0 string)) *MockStore_LoadFromDBOrGenesisFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockStore_LoadFromDBOrGenesisFile_Call) Return(_a0 State, _a1 error) *MockStore_LoadFromDBOrGenesisFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_LoadFromDBOrGenesisFile_Call) RunAndReturn(run func(string) (State, error)) *MockStore_LoadFromDBOrGenesisFile_Call {
	_c.Call.Return(run)
	return _c
}

// LoadLastABCIResponse provides a mock function with given fields: _a0
func (_m *MockStore) LoadLastABCIResponse(_a0 int64) (*tendermintstate.ABCIResponses, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for LoadLastABCIResponse")
	}

	var r0 *tendermintstate.ABCIResponses
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*tendermintstate.ABCIResponses, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(int64) *tendermintstate.ABCIResponses); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tendermintstate.ABCIResponses)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_LoadLastABCIResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadLastABCIResponse'
type MockStore_LoadLastABCIResponse_Call struct {
	*mock.Call
}

// LoadLastABCIResponse is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockStore_Expecter) LoadLastABCIResponse(_a0 interface{}) *MockStore_LoadLastABCIResponse_Call {
	return &MockStore_LoadLastABCIResponse_Call{Call: _e.mock.On("LoadLastABCIResponse", _a0)}
}

func (_c *MockStore_LoadLastABCIResponse_Call) Run(run func(_a0 int64)) *MockStore_LoadLastABCIResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockStore_LoadLastABCIResponse_Call) Return(_a0 *tendermintstate.ABCIResponses, _a1 error) *MockStore_LoadLastABCIResponse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_LoadLastABCIResponse_Call) RunAndReturn(run func(int64) (*tendermintstate.ABCIResponses, error)) *MockStore_LoadLastABCIResponse_Call {
	_c.Call.Return(run)
	return _c
}

// LoadLastHeightConsensusParamsChanged provides a mock function with given fields: height
func (_m *MockStore) LoadLastHeightConsensusParamsChanged(height int64) (int64, error) {
	ret := _m.Called(height)

	if len(ret) == 0 {
		panic("no return value specified for LoadLastHeightConsensusParamsChanged")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (int64, error)); ok {
		return rf(height)
	}
	if rf, ok := ret.Get(0).(func(int64) int64); ok {
		r0 = rf(height)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(height)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_LoadLastHeightConsensusParamsChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadLastHeightConsensusParamsChanged'
type MockStore_LoadLastHeightConsensusParamsChanged_Call struct {
	*mock.Call
}

// LoadLastHeightConsensusParamsChanged is a helper method to define mock.On call
//   - height int64
func (_e *MockStore_Expecter) LoadLastHeightConsensusParamsChanged(height interface{}) *MockStore_LoadLastHeightConsensusParamsChanged_Call {
	return &MockStore_LoadLastHeightConsensusParamsChanged_Call{Call: _e.mock.On("LoadLastHeightConsensusParamsChanged", height)}
}

func (_c *MockStore_LoadLastHeightConsensusParamsChanged_Call) Run(run func(height int64)) *MockStore_LoadLastHeightConsensusParamsChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockStore_LoadLastHeightConsensusParamsChanged_Call) Return(_a0 int64, _a1 error) *MockStore_LoadLastHeightConsensusParamsChanged_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_LoadLastHeightConsensusParamsChanged_Call) RunAndReturn(run func(int64) (int64, error)) *MockStore_LoadLastHeightConsensusParamsChanged_Call {
	_c.Call.Return(run)
	return _c
}

// LoadLastHeightValidatorsChanged provides a mock function with given fields: height
func (_m *MockStore) LoadLastHeightValidatorsChanged(height int64) (int64, error) {
	ret := _m.Called(height)

	if len(ret) == 0 {
		panic("no return value specified for LoadLastHeightValidatorsChanged")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (int64, error)); ok {
		return rf(height)
	}
	if rf, ok := ret.Get(0).(func(int64) int64); ok {
		r0 = rf(height)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(height)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_LoadLastHeightValidatorsChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadLastHeightValidatorsChanged'
type MockStore_LoadLastHeightValidatorsChanged_Call struct {
	*mock.Call
}

// LoadLastHeightValidatorsChanged is a helper method to define mock.On call
//   - height int64
func (_e *MockStore_Expecter) LoadLastHeightValidatorsChanged(height interface{}) *MockStore_LoadLastHeightValidatorsChanged_Call {
	return &MockStore_LoadLastHeightValidatorsChanged_Call{Call: _e.mock.On("LoadLastHeightValidatorsChanged", height)}
}

func (_c *MockStore_LoadLastHeightValidatorsChanged_Call) Run(run func(height int64)) *MockStore_LoadLastHeightValidatorsChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockStore_LoadLastHeightValidatorsChanged_Call) Return(_a0 int64, _a1 error) *MockStore_LoadLastHeightValidatorsChanged_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_LoadLastHeightValidatorsChanged_Call) RunAndReturn(run func(int64) (int64, error)) *MockStore_LoadLastHeightValidatorsChanged_Call {
	_c.Call.Return(run)
	return _c
}

// LoadValidators provides a mock function with given fields: _a0
func (_m *MockStore) LoadValidators(_a0 int64) (*types.ValidatorSet, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for LoadValidators")
	}

	var r0 *types.ValidatorSet
	var r1 error
	if rf, ok := ret.Get(0).(func(int64) (*types.ValidatorSet, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(int64) *types.ValidatorSet); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ValidatorSet)
		}
	}

	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_LoadValidators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadValidators'
type MockStore_LoadValidators_Call struct {
	*mock.Call
}

// LoadValidators is a helper method to define mock.On call
//   - _a0 int64
func (_e *MockStore_Expecter) LoadValidators(_a0 interface{}) *MockStore_LoadValidators_Call {
	return &MockStore_LoadValidators_Call{Call: _e.mock.On("LoadValidators", _a0)}
}

func (_c *MockStore_LoadValidators_Call) Run(run func(_a0 int64)) *MockStore_LoadValidators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64))
	})
	return _c
}

func (_c *MockStore_LoadValidators_Call) Return(_a0 *types.ValidatorSet, _a1 error) *MockStore_LoadValidators_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_LoadValidators_Call) RunAndReturn(run func(int64) (*types.ValidatorSet, error)) *MockStore_LoadValidators_Call {
	_c.Call.Return(run)
	return _c
}

// PruneStates provides a mock function with given fields: _a0, _a1
func (_m *MockStore) PruneStates(_a0 int64, _a1 int64) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PruneStates")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, int64) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_PruneStates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneStates'
type MockStore_PruneStates_Call struct {
	*mock.Call
}

// PruneStates is a helper method to define mock.On call
//   - _a0 int64
//   - _a1 int64
func (_e *MockStore_Expecter) PruneStates(_a0 interface{}, _a1 interface{}) *MockStore_PruneStates_Call {
	return &MockStore_PruneStates_Call{Call: _e.mock.On("PruneStates", _a0, _a1)}
}

func (_c *MockStore_PruneStates_Call) Run(run func(_a0 int64, _a1 int64)) *MockStore_PruneStates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(int64))
	})
	return _c
}

func (_c *MockStore_PruneStates_Call) Return(_a0 error) *MockStore_PruneStates_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_PruneStates_Call) RunAndReturn(run func(int64, int64) error) *MockStore_PruneStates_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: _a0
func (_m *MockStore) Save(_a0 State) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(State) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - _a0 State
func (_e *MockStore_Expecter) Save(_a0 interface{}) *MockStore_Save_Call {
	return &MockStore_Save_Call{Call: _e.mock.On("Save", _a0)}
}

func (_c *MockStore_Save_Call) Run(run func(_a0 State)) *MockStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(State))
	})
	return _c
}

func (_c *MockStore_Save_Call) Return(_a0 error) *MockStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Save_Call) RunAndReturn(run func(State) error) *MockStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveABCIResponses provides a mock function with given fields: _a0, _a1
func (_m *MockStore) SaveABCIResponses(_a0 int64, _a1 *tendermintstate.ABCIResponses) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SaveABCIResponses")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, *tendermintstate.ABCIResponses) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_SaveABCIResponses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveABCIResponses'
type MockStore_SaveABCIResponses_Call struct {
	*mock.Call
}

// SaveABCIResponses is a helper method to define mock.On call
//   - _a0 int64
//   - _a1 *tendermintstate.ABCIResponses
func (_e *MockStore_Expecter) SaveABCIResponses(_a0 interface{}, _a1 interface{}) *MockStore_SaveABCIResponses_Call {
	return &MockStore_SaveABCIResponses_Call{Call: _e.mock.On("SaveABCIResponses", _a0, _a1)}
}

func (_c *MockStore_SaveABCIResponses_Call) Run(run func(_a0 int64, _a1 *tendermintstate.ABCIResponses)) *MockStore_SaveABCIResponses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(*tendermintstate.ABCIResponses))
	})
	return _c
}

func (_c *MockStore_SaveABCIResponses_Call) Return(_a0 error) *MockStore_SaveABCIResponses_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_SaveABCIResponses_Call) RunAndReturn(run func(int64, *tendermintstate.ABCIResponses) error) *MockStore_SaveABCIResponses_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
