// Code generated by mockery. DO NOT EDIT.

package mempool

import (
	abcitypes "github.com/cometbft/cometbft/abci/types"
	mock "github.com/stretchr/testify/mock"

	types "github.com/cometbft/cometbft/types"
)

// MockMempool is an autogenerated mock type for the Mempool type
type MockMempool struct {
	mock.Mock
}

type MockMempool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMempool) EXPECT() *MockMempool_Expecter {
	return &MockMempool_Expecter{mock: &_m.Mock}
}

// CheckTx provides a mock function with given fields: tx, callback, txInfo
func (_m *MockMempool) CheckTx(tx types.Tx, callback func(*abcitypes.Response), txInfo TxInfo) error {
	ret := _m.Called(tx, callback, txInfo)

	if len(ret) == 0 {
		panic("no return value specified for CheckTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.Tx, func(*abcitypes.Response), TxInfo) error); ok {
		r0 = rf(tx, callback, txInfo)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMempool_CheckTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckTx'
type MockMempool_CheckTx_Call struct {
	*mock.Call
}

// CheckTx is a helper method to define mock.On call
//   - tx types.Tx
//   - callback func(*abcitypes.Response)
//   - txInfo TxInfo
func (_e *MockMempool_Expecter) CheckTx(tx interface{}, callback interface{}, txInfo interface{}) *MockMempool_CheckTx_Call {
	return &MockMempool_CheckTx_Call{Call: _e.mock.On("CheckTx", tx, callback, txInfo)}
}

func (_c *MockMempool_CheckTx_Call) Run(run func(tx types.Tx, callback func(*abcitypes.Response), txInfo TxInfo)) *MockMempool_CheckTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.Tx), args[1].(func(*abcitypes.Response)), args[2].(TxInfo))
	})
	return _c
}

func (_c *MockMempool_CheckTx_Call) Return(_a0 error) *MockMempool_CheckTx_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMempool_CheckTx_Call) RunAndReturn(run func(types.Tx, func(*abcitypes.Response), TxInfo) error) *MockMempool_CheckTx_Call {
	_c.Call.Return(run)
	return _c
}

// EnableTxsAvailable provides a mock function with no fields
func (_m *MockMempool) EnableTxsAvailable() {
	_m.Called()
}

// MockMempool_EnableTxsAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableTxsAvailable'
type MockMempool_EnableTxsAvailable_Call struct {
	*mock.Call
}

// EnableTxsAvailable is a helper method to define mock.On call
func (_e *MockMempool_Expecter) EnableTxsAvailable() *MockMempool_EnableTxsAvailable_Call {
	return &MockMempool_EnableTxsAvailable_Call{Call: _e.mock.On("EnableTxsAvailable")}
}

func (_c *MockMempool_EnableTxsAvailable_Call) Run(run func()) *MockMempool_EnableTxsAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMempool_EnableTxsAvailable_Call) Return() *MockMempool_EnableTxsAvailable_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMempool_EnableTxsAvailable_Call) RunAndReturn(run func()) *MockMempool_EnableTxsAvailable_Call {
	_c.Run(run)
	return _c
}

// Flush provides a mock function with no fields
func (_m *MockMempool) Flush() {
	_m.Called()
}

// MockMempool_Flush_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Flush'
type MockMempool_Flush_Call struct {
	*mock.Call
}

// Flush is a helper method to define mock.On call
func (_e *MockMempool_Expecter) Flush() *MockMempool_Flush_Call {
	return &MockMempool_Flush_Call{Call: _e.mock.On("Flush")}
}

func (_c *MockMempool_Flush_Call) Run(run func()) *MockMempool_Flush_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMempool_Flush_Call) Return() *MockMempool_Flush_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMempool_Flush_Call) RunAndReturn(run func()) *MockMempool_Flush_Call {
	_c.Run(run)
	return _c
}

// FlushAppConn provides a mock function with no fields
func (_m *MockMempool) FlushAppConn() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FlushAppConn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMempool_FlushAppConn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FlushAppConn'
type MockMempool_FlushAppConn_Call struct {
	*mock.Call
}

// FlushAppConn is a helper method to define mock.On call
func (_e *MockMempool_Expecter) FlushAppConn() *MockMempool_FlushAppConn_Call {
	return &MockMempool_FlushAppConn_Call{Call: _e.mock.On("FlushAppConn")}
}

func (_c *MockMempool_FlushAppConn_Call) Run(run func()) *MockMempool_FlushAppConn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMempool_FlushAppConn_Call) Return(_a0 error) *MockMempool_FlushAppConn_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMempool_FlushAppConn_Call) RunAndReturn(run func() error) *MockMempool_FlushAppConn_Call {
	_c.Call.Return(run)
	return _c
}

// Lock provides a mock function with no fields
func (_m *MockMempool) Lock() {
	_m.Called()
}

// MockMempool_Lock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lock'
type MockMempool_Lock_Call struct {
	*mock.Call
}

// Lock is a helper method to define mock.On call
func (_e *MockMempool_Expecter) Lock() *MockMempool_Lock_Call {
	return &MockMempool_Lock_Call{Call: _e.mock.On("Lock")}
}

func (_c *MockMempool_Lock_Call) Run(run func()) *MockMempool_Lock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMempool_Lock_Call) Return() *MockMempool_Lock_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMempool_Lock_Call) RunAndReturn(run func()) *MockMempool_Lock_Call {
	_c.Run(run)
	return _c
}

// ReapMaxTxs provides a mock function with given fields: max
func (_m *MockMempool) ReapMaxTxs(max int) types.Txs {
	ret := _m.Called(max)

	if len(ret) == 0 {
		panic("no return value specified for ReapMaxTxs")
	}

	var r0 types.Txs
	if rf, ok := ret.Get(0).(func(int) types.Txs); ok {
		r0 = rf(max)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Txs)
		}
	}

	return r0
}

// MockMempool_ReapMaxTxs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReapMaxTxs'
type MockMempool_ReapMaxTxs_Call struct {
	*mock.Call
}

// ReapMaxTxs is a helper method to define mock.On call
//   - max int
func (_e *MockMempool_Expecter) ReapMaxTxs(max interface{}) *MockMempool_ReapMaxTxs_Call {
	return &MockMempool_ReapMaxTxs_Call{Call: _e.mock.On("ReapMaxTxs", max)}
}

func (_c *MockMempool_ReapMaxTxs_Call) Run(run func(max int)) *MockMempool_ReapMaxTxs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockMempool_ReapMaxTxs_Call) Return(_a0 types.Txs) *MockMempool_ReapMaxTxs_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMempool_ReapMaxTxs_Call) RunAndReturn(run func(int) types.Txs) *MockMempool_ReapMaxTxs_Call {
	_c.Call.Return(run)
	return _c
}

// ReapMaxTxsMaxBytesMaxGas provides a mock function with given fields: maxTxs, maxBytes, maxGas
func (_m *MockMempool) ReapMaxTxsMaxBytesMaxGas(maxTxs int, maxBytes int64, maxGas int64) types.Txs {
	ret := _m.Called(maxTxs, maxBytes, maxGas)

	if len(ret) == 0 {
		panic("no return value specified for ReapMaxTxsMaxBytesMaxGas")
	}

	var r0 types.Txs
	if rf, ok := ret.Get(0).(func(int, int64, int64) types.Txs); ok {
		r0 = rf(maxTxs, maxBytes, maxGas)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.Txs)
		}
	}

	return r0
}

// MockMempool_ReapMaxTxsMaxBytesMaxGas_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReapMaxTxsMaxBytesMaxGas'
type MockMempool_ReapMaxTxsMaxBytesMaxGas_Call struct {
	*mock.Call
}

// ReapMaxTxsMaxBytesMaxGas is a helper method to define mock.On call
//   - maxTxs int
//   - maxBytes int64
//   - maxGas int64
func (_e *MockMempool_Expecter) ReapMaxTxsMaxBytesMaxGas(maxTxs interface{}, maxBytes interface{}, maxGas interface{}) *MockMempool_ReapMaxTxsMaxBytesMaxGas_Call {
	return &MockMempool_ReapMaxTxsMaxBytesMaxGas_Call{Call: _e.mock.On("ReapMaxTxsMaxBytesMaxGas", maxTxs, maxBytes, maxGas)}
}

func (_c *MockMempool_ReapMaxTxsMaxBytesMaxGas_Call) Run(run func(maxTxs int, maxBytes int64, maxGas int64)) *MockMempool_ReapMaxTxsMaxBytesMaxGas_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *MockMempool_ReapMaxTxsMaxBytesMaxGas_Call) Return(_a0 types.Txs) *MockMempool_ReapMaxTxsMaxBytesMaxGas_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMempool_ReapMaxTxsMaxBytesMaxGas_Call) RunAndReturn(run func(int, int64, int64) types.Txs) *MockMempool_ReapMaxTxsMaxBytesMaxGas_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTxByKey provides a mock function with given fields: txKey
func (_m *MockMempool) RemoveTxByKey(txKey types.TxKey) error {
	ret := _m.Called(txKey)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTxByKey")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(types.TxKey) error); ok {
		r0 = rf(txKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMempool_RemoveTxByKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTxByKey'
type MockMempool_RemoveTxByKey_Call struct {
	*mock.Call
}

// RemoveTxByKey is a helper method to define mock.On call
//   - txKey types.TxKey
func (_e *MockMempool_Expecter) RemoveTxByKey(txKey interface{}) *MockMempool_RemoveTxByKey_Call {
	return &MockMempool_RemoveTxByKey_Call{Call: _e.mock.On("RemoveTxByKey", txKey)}
}

func (_c *MockMempool_RemoveTxByKey_Call) Run(run func(txKey types.TxKey)) *MockMempool_RemoveTxByKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(types.TxKey))
	})
	return _c
}

func (_c *MockMempool_RemoveTxByKey_Call) Return(_a0 error) *MockMempool_RemoveTxByKey_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMempool_RemoveTxByKey_Call) RunAndReturn(run func(types.TxKey) error) *MockMempool_RemoveTxByKey_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function with no fields
func (_m *MockMempool) Size() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockMempool_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockMempool_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockMempool_Expecter) Size() *MockMempool_Size_Call {
	return &MockMempool_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockMempool_Size_Call) Run(run func()) *MockMempool_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMempool_Size_Call) Return(_a0 int) *MockMempool_Size_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMempool_Size_Call) RunAndReturn(run func() int) *MockMempool_Size_Call {
	_c.Call.Return(run)
	return _c
}

// SizeBytes provides a mock function with no fields
func (_m *MockMempool) SizeBytes() int64 {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for SizeBytes")
	}

	var r0 int64
	if rf, ok := ret.Get(0).(func() int64); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int64)
	}

	return r0
}

// MockMempool_SizeBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SizeBytes'
type MockMempool_SizeBytes_Call struct {
	*mock.Call
}

// SizeBytes is a helper method to define mock.On call
func (_e *MockMempool_Expecter) SizeBytes() *MockMempool_SizeBytes_Call {
	return &MockMempool_SizeBytes_Call{Call: _e.mock.On("SizeBytes")}
}

func (_c *MockMempool_SizeBytes_Call) Run(run func()) *MockMempool_SizeBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMempool_SizeBytes_Call) Return(_a0 int64) *MockMempool_SizeBytes_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMempool_SizeBytes_Call) RunAndReturn(run func() int64) *MockMempool_SizeBytes_Call {
	_c.Call.Return(run)
	return _c
}

// TxsAvailable provides a mock function with no fields
func (_m *MockMempool) TxsAvailable() <-chan struct{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for TxsAvailable")
	}

	var r0 <-chan struct{}
	if rf, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	return r0
}

// MockMempool_TxsAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TxsAvailable'
type MockMempool_TxsAvailable_Call struct {
	*mock.Call
}

// TxsAvailable is a helper method to define mock.On call
func (_e *MockMempool_Expecter) TxsAvailable() *MockMempool_TxsAvailable_Call {
	return &MockMempool_TxsAvailable_Call{Call: _e.mock.On("TxsAvailable")}
}

func (_c *MockMempool_TxsAvailable_Call) Run(run func()) *MockMempool_TxsAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMempool_TxsAvailable_Call) Return(_a0 <-chan struct{}) *MockMempool_TxsAvailable_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMempool_TxsAvailable_Call) RunAndReturn(run func() <-chan struct{}) *MockMempool_TxsAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// Unlock provides a mock function with no fields
func (_m *MockMempool) Unlock() {
	_m.Called()
}

// MockMempool_Unlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unlock'
type MockMempool_Unlock_Call struct {
	*mock.Call
}

// Unlock is a helper method to define mock.On call
func (_e *MockMempool_Expecter) Unlock() *MockMempool_Unlock_Call {
	return &MockMempool_Unlock_Call{Call: _e.mock.On("Unlock")}
}

func (_c *MockMempool_Unlock_Call) Run(run func()) *MockMempool_Unlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMempool_Unlock_Call) Return() *MockMempool_Unlock_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMempool_Unlock_Call) RunAndReturn(run func()) *MockMempool_Unlock_Call {
	_c.Run(run)
	return _c
}

// Update provides a mock function with given fields: blockHeight, blockTxs, deliverTxResponses, newPreFn, newPostFn
func (_m *MockMempool) Update(blockHeight int64, blockTxs types.Txs, deliverTxResponses []*abcitypes.ResponseDeliverTx, newPreFn PreCheckFunc, newPostFn PostCheckFunc) error {
	ret := _m.Called(blockHeight, blockTxs, deliverTxResponses, newPreFn, newPostFn)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(int64, types.Txs, []*abcitypes.ResponseDeliverTx, PreCheckFunc, PostCheckFunc) error); ok {
		r0 = rf(blockHeight, blockTxs, deliverTxResponses, newPreFn, newPostFn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMempool_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockMempool_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - blockHeight int64
//   - blockTxs types.Txs
//   - deliverTxResponses []*abcitypes.ResponseDeliverTx
//   - newPreFn PreCheckFunc
//   - newPostFn PostCheckFunc
func (_e *MockMempool_Expecter) Update(blockHeight interface{}, blockTxs interface{}, deliverTxResponses interface{}, newPreFn interface{}, newPostFn interface{}) *MockMempool_Update_Call {
	return &MockMempool_Update_Call{Call: _e.mock.On("Update", blockHeight, blockTxs, deliverTxResponses, newPreFn, newPostFn)}
}

func (_c *MockMempool_Update_Call) Run(run func(blockHeight int64, blockTxs types.Txs, deliverTxResponses []*abcitypes.ResponseDeliverTx, newPreFn PreCheckFunc, newPostFn PostCheckFunc)) *MockMempool_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int64), args[1].(types.Txs), args[2].([]*abcitypes.ResponseDeliverTx), args[3].(PreCheckFunc), args[4].(PostCheckFunc))
	})
	return _c
}

func (_c *MockMempool_Update_Call) Return(_a0 error) *MockMempool_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMempool_Update_Call) RunAndReturn(run func(int64, types.Txs, []*abcitypes.ResponseDeliverTx, PreCheckFunc, PostCheckFunc) error) *MockMempool_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMempool creates a new instance of MockMempool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMempool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMempool {
	mock := &MockMempool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
